spring:
  application:
    name: AccountMS
server:
  port: 9095
management:
  endpoints:
    web:
      exposure:
        include: "*"
tokenExpiryInterval: 600000
token_message: valid
policy:
  GET:
   summary: CUSTOMER_ROLE, ADMIN_ROLE
   current_balance: CUSTOMER_ROLE
   due: CUSTOMER_ROLE
