spring:
  application:
    name: CustomerMS
endpoints:
  authorize: http://localhost:9091/token/authorize
authorizer:
  enabled: true
server:
  port: 9093
message1: "Hello from config server"
management:
  endpoints:
    web:
      exposure:
        include: "*"
