GET http://localhost:9093/profile/address HTTP/1.1
Content-Type: application/json
Authorization: eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.YKIZT9iEs-aiF9t7KxUB5S9j6ti05EGgn_ylkUJbV8m2i4oKbGJ46zJnN-bjBiRg8ZY-fD3bbUnvEj_5H4poEnZsVMlVrZTfWrz0hY5SjGK5tkkg2vt8wMIYU9D8iDDyxrjhP6IVadLG-whErmYIy2ozlWD3C1bbdmAHjTVw-DiI9LJZ1Ym4pbrqiyrpIOhF-JmLGBnF4rQi_zkeuosEQbUsrmeFhQ-JPtNUyd2VBWevSht0xxCMMiSoUR1F78CtoKa7VF6lU6T0IKTBKb_CtSGAeW3dt9tp-5xsvE7_VEA3BzRN0IPy-Okyu0qSgnLjdd-RTBIoIBu36n0Fk3MIXg.Z_H35AZw_JV_jBaDZEjPcA.YQ750wn_oFAJSRD2VOOcnAYrC7af3ERjSF6M2q8eRdTOd7EIgLZtHIO0H2BD306FkdOUT642LU5lttakEv708VsIA0dMjA8BpYaArx3zPeDluZLmFmDxKCHNRIJOx-5kl2MdGYBEru5gnwiaOS4YrKIB-u3U40bPu_aNV0mADumdk4Rxos8ABvQI28sJYbmzbeGdg9eYHi_0zafLXgKUdHV07_aceiFkZ_i9ZJWHlewO81c-85DWNiQHlrS-eU3v82cciBnJ4EWR-jc35QZAsQ.PtxyfB7GFcHMHblpjjXRdQ