GET http://localhost:9093/profile/email HTTP/1.1
Content-Type: application/json
Authorization: eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.3_mZQJzsSniKgXuJw45KFYtYJQRVCfAQXHz5kJDxioGjHHI1sQS0ghM9kgkSa7vOVRKeIfc6MItQFBo30wVJAlXjYXef0dp9miijQ0YpOOgYqKWVZmZWqD1VbBZcSjDjVcLELBFarhjxfyvqeCvJMNsqcIkxyEsnUMUc2fNUCIdXG3jqRR9NmvwlZLikvdmdJaofJkmC5pVAMgNvpMiOMLOLdVAUi0yTjaSte-iKnot_0Z1g1Fc3C5n2x60EfLZEB8LUmHyrUqD5Hog3OzSS5VXTRrlHPnAuhaCuV-3QC-r0tyI-GNMpnbCjCFm4oo4R3nVTTXlB_saGm3SN9SGJww.BHsFA5k_-NrHW7mTzgY1zA.lG1x9mmQw7dhZODGeUUhNnMkEtQ68ur3AXvRoQdtnk9SHT5bfmme7R5aBdFthdwOm5e2bSnqNxeLuwWqnvFS1u5pyiyp_zK1HTl2NFsCWmK5ukMlF4OrnBpY6hFF3uUFwENLeMd2K3a2zZoaA1lyqg4B8dq5Bl76jDwflXAJ3Pnk9L7VMGfvbQD2Rlo-2X9K90jwlKw4BBUfscVnmler8q8fPeKo6TWDZA9l0MbpBqJdljpHGSxfmHojhkIUFIyJvTy-8eq_1sJYc8wzo4u3HoTaTc0g-2vJ_r-fjrNN3oo.08aNjtLvYAmnu_wVLWIyvw