GET http://localhost:9093/profile/email HTTP/1.1
Content-Type: application/json
Authorization: eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.Fj8UGfTTV-oyYXnI7mzR2PGPMaX7C14m1_5U8n6tIvfBajN6FwPWbs6afIuUEvsNih_HxaFsjWp-_ua3lXY8avKE-DPyqhZ4fHnGLei3007VnPWgt4-zjF1fJ9SOcq5ay6K5rEFZuGAdmJilsq6120fuHqdEt8qGd3y3Xr5Sb9O__LDwe6lF8u_QfJncYB3zcjgAEDgi1HVUuyKUasVJrgrssg2f2Uxkf9HPJuPNOeXoWVYkoUjNTsx2UVH7o1zGhJOOWt6luQeQz6-yJjvdMnE-VI1qEMbNfFAcaFbf3y_yCTeYzFtdGpIgwxflvboVTLYLuB0owLcAUeIooGQjtA.cCC17UIwNYu0JEvPJXbZkw.1nuaMjBoUlZ8w_jJKSLIqCsnOJjG8cKNSEEiM_lHmbaFiJWQLZKPyNb5B7bNiBXFJZymCfydXYc3H13ndTBf5AULuR9T0ngkujTZ7hZFDTMw9EngfoUA5nZkBXJef43lQmHVm0GCbUlQa3-ax1f2bS_zaPAmXO8ucnzLn1Ehx1tN2haarm6Q_UPtQncL9GxL2xQe9P6LXI8s47iNb06B6hOohxSAe8FoRejqEyvLPQFGAvUtfmlQ7uluLSLpuGzvBTTXwmqNVHYDetT_StDFFA.wcLdvp1EeYQ1kD3Dqw43mg