spring:
  application:
    name: TransactionMS
server:
  port: 9096
management:
  endpoints:
    web:
      exposure:
        include: "*"
tokenExpiryInterval: 600000
token_message: valid
policy:
  GET:
   summary: CUSTOMER_ROLE, ADMIN_ROLE
   recent: CUSTOMER_ROLE
   last: CUSTOMER_ROLE
