apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-crud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account-crud
    spec:
      containers:
      - name: account-crud
        image: pnkjsmwl/account-crud:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8095
      imagePullSecrets:
      - name: my-sec