---
 apiVersion: v1
 kind: Service
 metadata:
   name: account
   namespace: domain
 spec:
   ports:
     - port: 80
       targetPort: 9095
   selector:
     app: account
   type: ClusterIP