apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configmap
  namespace: domain
data:
  CLOUD_CONFIG_URI: "http://configserver"
  ACCOUNT_CRUD_URL: "http://account-crud.crud"
  TRANSACTION_CRUD_URL: "http://transaction-crud.crud"
  PROFILE_CRUD_URL: "http://customerprofile-crud.crud"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: domain
data:
  REDIS_HOST: "myredis.grfk6k.0001.use1.cache.amazonaws.com"
  REDIS_HOST_SEC: "myredis.yhjlx0.0001.use2.cache.amazonaws.com"
  REDIS_PORT: "6379" 
  REDIS_TIMEOUT: "3000"  