---
 apiVersion: v1
 kind: Service
 metadata:
   name: configserver
   namespace: domain
 spec:
   ports:
     - port: 80
       targetPort: 8080
   selector:
     app: configserver
   type: ClusterIP