---
 apiVersion: v1
 kind: Service
 metadata:
   name: customerprofile-crud
 spec:
   ports:
     - port: 80
       targetPort: 8097
   selector:
     app: customerprofile-crud
   type: ClusterIP