---
 apiVersion: v1
 kind: Service
 metadata:
   name: customerprofile
   namespace: domain
 spec:
   ports:
     - port: 80
       targetPort: 9097
   selector:
     app: customerprofile
   type: ClusterIP