---
 apiVersion: v1
 kind: Service
 metadata:
   name: transaction-crud
   namespace: crud
 spec:
   ports:
     - port: 80
       targetPort: 8096
   selector:
     app: transaction-crud
   type: ClusterIP