---
 apiVersion: v1
 kind: Service
 metadata:
   name: transaction
   namespace: domain
 spec:
   ports:
     - port: 80
       targetPort: 9096
   selector:
     app: transaction
   type: ClusterIP