apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transaction
  namespace: domain
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction
        image: pnkjsmwl/transaction:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9096
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-configmap
              key: REDIS_HOST
        - name: REDIS_HOST_SEC
          valueFrom:
            configMapKeyRef:
              name: redis-configmap
              key: REDIS_HOST_SEC      
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-configmap
              key: REDIS_PORT
        - name: REDIS_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: redis-configmap
              key: REDIS_TIMEOUT
        - name: CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              name: service-configmap
              key: CLOUD_CONFIG_URI
        - name: TRANSACTION_CRUD_URL
          valueFrom:
            configMapKeyRef:
              name: service-configmap
              key: TRANSACTION_CRUD_URL
      imagePullSecrets:
      - name: my-sec