package com.demo.token.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "user_info")
public class UserInfo {

	public UserInfo(){}

	private String id;
	private String userName;
	private String password;
	private String accountNumber;
	private String role;
	private String arn;

	public UserInfo(String id, String userName, String password, String accountNumber, String role) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.accountNumber = accountNumber;
		this.role = role;
	}

	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "id")
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBHashKey(attributeName="userName") 
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	@DynamoDBAttribute(attributeName="password") 
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	@DynamoDBAttribute(attributeName="accountNumber") 
	public String getAccountNumber() {
		return accountNumber;
	}
	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}
	@DynamoDBAttribute(attributeName="role") 
	public String getRole() {
		return role;
	}
	public void setRole(String role) {
		this.role = role;
	}
	@DynamoDBIgnore
	public String getArn() {
		return arn;
	}
	public void setArn(String arn) {
		this.arn = arn;
	}



}