package com.demo.token.dao;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

@DynamoDBTable(tableName = "user_info")
public class UserInfo {

	public UserInfo(){}

	private String id;
	private String userName;
	private String password;
	private String email;
	private String phone;
	private List<AccountInfo> account;
	private String arn;
	private String redisKey;

	public UserInfo(String userName, String arn, String redisKey) {
		this.userName = userName;
		this.arn = arn;
		this.redisKey = redisKey;
	}
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName = "id")
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute
	@DynamoDBHashKey(attributeName="userName") 
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	@DynamoDBAttribute(attributeName="password") 
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	@DynamoDBAttribute(attributeName="email")
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@DynamoDBAttribute(attributeName="phone")
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	@DynamoDBAttribute(attributeName="account")
	@DynamoDBTypeConvertedEnum
	@DynamoDBTypeConverted(converter = AccountConverter.class)
	public List<AccountInfo> getAccount() {
		return account;
	}
	public void setAccount(List<AccountInfo> account) {
		this.account = account;
	}
	@DynamoDBIgnore
	public String getArn() {
		return arn;
	}
	public void setArn(String arn) {
		this.arn = arn;
	}
	@DynamoDBIgnore
	public String getRedisKey() {
		return redisKey;
	}
	public void setRedisKey(String redisKey) {
		this.redisKey = redisKey;
	}




}